"""
Toponymy Engine — Procedural Naming
=====================================
Each kingdom has a 'linguistic seed' (a set of phoneme patterns).
Names are generated by chaining prefix + vowel cluster + suffix patterns.
Kingdoms near mountains get harsh consonants; coastal kingdoms get softer names.
"""
from __future__ import annotations

import math
import random


# Linguistic seeds keyed by culture archetype
CULTURES = [
    {   # Elvish / Arcane
        "prefixes": ["Ael", "Syl", "Myr", "Aer", "Cal", "Ith", "Val", "Nael"],
        "middles":  ["an", "in", "or", "ar", "en", "ir", "al", "el"],
        "suffixes": ["dor", "thel", "rion", "shan", "wyn", "mir", "fel", "las"],
    },
    {   # Dwarven / Nordic
        "prefixes": ["Gor", "Brak", "Thur", "Dur", "Krag", "Orm", "Sten", "Brom"],
        "middles":  ["ak", "um", "ok", "ik", "ul", "am"],
        "suffixes": ["heim", "gard", "dal", "fell", "thar", "mund", "brek", "kel"],
    },
    {   # Eastern / Silk-road
        "prefixes": ["Xan", "Jian", "Wei", "Han", "Zhao", "Tang", "Liang", "Shi"],
        "middles":  ["zh", "g", "n", "ng", "xi", "li"],
        "suffixes": ["zhou", "jing", "hai", "an", "ning", "yang", "ling", "hun"],
    },
    {   # Arabian / Desert
        "prefixes": ["Al", "Abd", "Um", "Ibn", "Kha", "Zar", "Nas", "Far"],
        "middles":  ["a", "i", "u", "ah", "id"],
        "suffixes": ["abad", "pur", "khan", "istan", "ara", "id", "zar", "aq"],
    },
    {   # Latin / Roman
        "prefixes": ["Mar", "Jul", "Aur", "Cas", "Val", "Tul", "Max", "Gal"],
        "middles":  ["ius", "ia", "ium", "us", "a"],
        "suffixes": ["opolis", "anum", "ium", "ia", "um", "uris", "alis", "ensis"],
    },
    {   # Slavic / Eastern European
        "prefixes": ["Bor", "Vlad", "Svat", "Mir", "Brat", "Nov", "Kiv", "Star"],
        "middles":  ["o", "a", "e", "y", "i"],
        "suffixes": ["grad", "gorod", "burg", "ov", "sk", "evo", "itz", "mir"],
    },
]

KINGDOM_EPITHETS = [
    "the Golden", "of the Stone", "the Verdant", "the Eternal",
    "of the Sea", "the Arcane", "the Iron", "of the Flame",
    "the Hidden", "the Ancient",
]


class ToponymyEngine:
    def __init__(self, seed: int):
        self._rng = random.Random(seed + 31415)
        self._kingdom_cultures: dict[int, dict] = {}

    def _culture_for(self, kingdom_id: int) -> dict:
        if kingdom_id not in self._kingdom_cultures:
            self._kingdom_cultures[kingdom_id] = self._rng.choice(CULTURES)
        return self._kingdom_cultures[kingdom_id]

    def kingdom_name(self, kingdom_id: int) -> str:
        c = self._culture_for(kingdom_id)
        prefix = self._rng.choice(c["prefixes"])
        suffix = self._rng.choice(c["suffixes"])
        epithet = self._rng.choice(KINGDOM_EPITHETS)
        return f"Kingdom of {prefix}{suffix} {epithet}"

    def city_name(self, kingdom_id: int, is_capital: bool = False) -> str:
        c = self._culture_for(kingdom_id)
        prefix = self._rng.choice(c["prefixes"])
        mid    = self._rng.choice(c["middles"])
        suffix = self._rng.choice(c["suffixes"])
        name = f"{prefix}{mid}{suffix}"
        if is_capital:
            capital_words = ["Capital", "Hold", "Throne", "Seat", "Citadel"]
            name += " " + self._rng.choice(capital_words)
        return name

    def region_name(self, kingdom_id: int) -> str:
        c = self._culture_for(kingdom_id)
        prefix = self._rng.choice(c["prefixes"])
        suffix = self._rng.choice(c["suffixes"])
        terrain_words = ["Plains", "Heights", "Vale", "Reaches", "Wastes",
                         "Marches", "Highlands", "Lowlands", "Coast", "Wilds"]
        return f"The {prefix}{suffix} {self._rng.choice(terrain_words)}"

    def ruin_name(self, kingdom_id: int) -> str:
        c = self._culture_for(kingdom_id)
        prefix = self._rng.choice(c["prefixes"])
        suffix = self._rng.choice(c["suffixes"])
        return f"Ruins of {prefix}{suffix}"
